spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CrusaderVII/Trello-config.git
          default-label: master

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
